"""Email exporter — sends cost reports via SES or SMTP.

Supports two backends:
  - ``ses``: AWS Simple Email Service (uses boto3)
  - ``smtp``: standard SMTP with TLS (stdlib smtplib, no extra deps)
"""

from __future__ import annotations

import html
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

import boto3

from .base import ExportResult


def _build_html_body(report: dict) -> str:
    # HTML-escape every interpolated value: service names, account, and period
    # can carry user-controlled strings (cost-category/tag-derived keys, a
    # profile name with markup), which any tag-capable principal could use to
    # inject HTML into the email. Mirrors the PDF renderer's esc().
    account = html.escape(str(report.get("account", "N/A")))
    period = html.escape(str(report.get("period", "N/A")))
    total = report.get("total_cost_usd", 0.0)
    top = report.get("top_services", [])

    rows = "".join(
        f"<tr><td>{html.escape(str(s.get('service', '')))}</td>"
        f"<td style='text-align:right'>${s.get('cost_usd', 0):.2f}</td></tr>"
        for s in top[:15]
    )
    audit = report.get("audit_summary", {})
    audit_section = ""
    if audit:
        audit_section = f"""
        <h3>FinOps Audit</h3>
        <p>Untagged resources: {audit.get('untagged', 0)}<br>
        Idle resources: {audit.get('idle', 0)}<br>
        Estimated monthly waste: ${audit.get('waste_usd', 0):.2f}</p>
        """

    return f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;max-width:700px;margin:auto">
  <h2 style="background:#232f3e;color:#fff;padding:12px 16px">AWS Cost Report</h2>
  <p><strong>Account:</strong> {account}<br>
  <strong>Period:</strong> {period}<br>
  <strong>Total Cost:</strong> ${total:,.2f} USD</p>
  <h3>Top Services</h3>
  <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%">
    <thead><tr style="background:#f5f5f5"><th>Service</th><th>Cost (USD)</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
  {audit_section}
  <p style="font-size:11px;color:#999">Generated by spendslicer</p>
</body>
</html>"""


def send_via_ses(
    report: dict,
    to_addresses: list[str],
    from_address: str,
    subject: str | None = None,
    attachment_path: str | Path | None = None,
    session: boto3.Session | None = None,
) -> ExportResult:
    """Send a cost report email via AWS SES."""
    subj = subject or f"AWS Cost Report — {report.get('account', '')} {report.get('period', '')}"
    dest = ", ".join(to_addresses)
    try:
        # SES sending identities are region-scoped; honour the session's
        # configured region (fall back to us-east-1 only if none is set), so an
        # account whose verified identity lives outside us-east-1 doesn't get
        # MessageRejected on every send.
        sess = session or boto3.Session()
        ses = sess.client("ses", region_name=sess.region_name or "us-east-1")

        if attachment_path:
            # Use raw MIME for attachments
            msg = MIMEMultipart("mixed")
            msg["Subject"] = subj
            msg["From"] = from_address
            msg["To"] = ", ".join(to_addresses)
            alt = MIMEMultipart("alternative")
            alt.attach(MIMEText(_build_html_body(report), "html"))
            msg.attach(alt)
            attach_path = Path(attachment_path)
            with attach_path.open("rb") as f:
                part = MIMEApplication(f.read(), Name=attach_path.name)
                part["Content-Disposition"] = f'attachment; filename="{attach_path.name}"'
                msg.attach(part)
            ses.send_raw_email(
                Source=from_address,
                Destinations=to_addresses,
                RawMessage={"Data": msg.as_string()},
            )
        else:
            ses.send_email(
                Source=from_address,
                Destination={"ToAddresses": to_addresses},
                Message={
                    "Subject": {"Data": subj},
                    "Body": {"Html": {"Data": _build_html_body(report)}},
                },
            )
        return ExportResult(format="email", destination=dest, success=True)
    except Exception as exc:
        return ExportResult(format="email", destination=dest, success=False, error=str(exc))
