"""Email exporter — sends cost reports via SES or SMTP.

Supports two backends:
  - ``ses``: AWS Simple Email Service (uses boto3)
  - ``smtp``: standard SMTP with TLS (stdlib smtplib, no extra deps)
"""

from __future__ import annotations

import smtplib
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path
from typing import Optional, Union

import boto3

from .base import ExportResult


def _build_html_body(report: dict) -> str:
    account = report.get("account", "N/A")
    period = report.get("period", "N/A")
    total = report.get("total_cost_usd", 0.0)
    top = report.get("top_services", [])

    rows = "".join(
        f"<tr><td>{s.get('service', '')}</td><td style='text-align:right'>${s.get('cost_usd', 0):.2f}</td></tr>"
        for s in top[:15]
    )
    audit = report.get("audit_summary", {})
    audit_section = ""
    if audit:
        audit_section = f"""
        <h3>FinOps Audit</h3>
        <p>Untagged resources: {audit.get('untagged', 0)}<br>
        Idle resources: {audit.get('idle', 0)}<br>
        Estimated monthly waste: ${audit.get('waste_usd', 0):.2f}</p>
        """

    return f"""<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;max-width:700px;margin:auto">
  <h2 style="background:#232f3e;color:#fff;padding:12px 16px">AWS Cost Report</h2>
  <p><strong>Account:</strong> {account}<br>
  <strong>Period:</strong> {period}<br>
  <strong>Total Cost:</strong> ${total:,.2f} USD</p>
  <h3>Top Services</h3>
  <table border="1" cellpadding="6" cellspacing="0" style="border-collapse:collapse;width:100%">
    <thead><tr style="background:#f5f5f5"><th>Service</th><th>Cost (USD)</th></tr></thead>
    <tbody>{rows}</tbody>
  </table>
  {audit_section}
  <p style="font-size:11px;color:#999">Generated by aws-cost-ultra</p>
</body>
</html>"""


def send_via_ses(
    report: dict,
    to_addresses: list[str],
    from_address: str,
    subject: Optional[str] = None,
    attachment_path: Optional[Union[str, Path]] = None,
    session: Optional[boto3.Session] = None,
) -> ExportResult:
    """Send a cost report email via AWS SES."""
    subj = subject or f"AWS Cost Report — {report.get('account', '')} {report.get('period', '')}"
    dest = ", ".join(to_addresses)
    try:
        ses = (session or boto3.Session()).client("ses", region_name="us-east-1")

        if attachment_path:
            # Use raw MIME for attachments
            msg = MIMEMultipart("mixed")
            msg["Subject"] = subj
            msg["From"] = from_address
            msg["To"] = ", ".join(to_addresses)
            alt = MIMEMultipart("alternative")
            alt.attach(MIMEText(_build_html_body(report), "html"))
            msg.attach(alt)
            attach_path = Path(attachment_path)
            with attach_path.open("rb") as f:
                part = MIMEApplication(f.read(), Name=attach_path.name)
                part["Content-Disposition"] = f'attachment; filename="{attach_path.name}"'
                msg.attach(part)
            ses.send_raw_email(
                Source=from_address,
                Destinations=to_addresses,
                RawMessage={"Data": msg.as_string()},
            )
        else:
            ses.send_email(
                Source=from_address,
                Destination={"ToAddresses": to_addresses},
                Message={
                    "Subject": {"Data": subj},
                    "Body": {"Html": {"Data": _build_html_body(report)}},
                },
            )
        return ExportResult(format="email", destination=dest, success=True)
    except Exception as exc:
        return ExportResult(format="email", destination=dest, success=False, error=str(exc))


def send_via_smtp(
    report: dict,
    to_addresses: list[str],
    from_address: str,
    smtp_host: str,
    smtp_port: int = 587,
    smtp_user: Optional[str] = None,
    smtp_password: Optional[str] = None,
    subject: Optional[str] = None,
    attachment_path: Optional[Union[str, Path]] = None,
) -> ExportResult:
    """Send a cost report email via SMTP (no extra dependencies)."""
    subj = subject or f"AWS Cost Report — {report.get('account', '')} {report.get('period', '')}"
    dest = ", ".join(to_addresses)
    try:
        msg = MIMEMultipart("mixed")
        msg["Subject"] = subj
        msg["From"] = from_address
        msg["To"] = ", ".join(to_addresses)
        alt = MIMEMultipart("alternative")
        alt.attach(MIMEText(_build_html_body(report), "html"))
        msg.attach(alt)

        if attachment_path:
            p = Path(attachment_path)
            with p.open("rb") as f:
                part = MIMEApplication(f.read(), Name=p.name)
                part["Content-Disposition"] = f'attachment; filename="{p.name}"'
                msg.attach(part)

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls()
            if smtp_user and smtp_password:
                server.login(smtp_user, smtp_password)
            server.sendmail(from_address, to_addresses, msg.as_string())

        return ExportResult(format="email", destination=dest, success=True)
    except Exception as exc:
        return ExportResult(format="email", destination=dest, success=False, error=str(exc))
